FROM solanalabs/rust:1.75.0
RUN sh -c "$(curl -sSfL https://release.solana.com/v1.18.4/install)" && \
    /root/.local/share/solana/install/active_release/bin/sdk/sbf/scripts/install.sh
ENV PATH=/root/.local/share/solana/install/active_release/bin:/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN cargo install --git https://github.com/coral-xyz/anchor --tag v0.29.0 avm --locked --force && \
    avm install 0.29.0 && avm use 0.29.0
RUN curl -fsSL https://dl.yarnpkg.com/debian/pubkey.gpg | \
    gpg --batch --yes --dearmor -o /usr/share/keyrings/yarn-archive-keyring.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/yarn-archive-keyring.gpg] https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
RUN curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
    gpg --batch --yes --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list
RUN apt update
RUN apt -y install yarn python3 net-tools
RUN apt clean && rm -rf /var/lib/apt/lists/* /var/lib/apt/cache/*
RUN solana-keygen new -f -s --no-bip39-passphrase
RUN solana config set --url http://localhost:8899
COPY . /photon-crosschain-messaging/
RUN yarn install --cwd /photon-crosschain-messaging/
COPY keys/*-keypair.json /photon-crosschain-messaging/target/deploy/
RUN --mount=type=cache,target=/photon-crosschain-messaging/target,sharing=locked --mount=type=cache,target=/usr/local/cargo/registry \
    cd /photon-crosschain-messaging/ && anchor build && \
    mkdir /deploy && \
    cp /photon-crosschain-messaging/target/deploy/onefunc.so /photon-crosschain-messaging/target/deploy/photon.so /deploy
WORKDIR /photon-crosschain-messaging/
RUN --mount=type=cache,target=/photon-crosschain-messaging/target docker/build_solana_test_state.sh
ENTRYPOINT ["solana-test-validator"]
