FROM rust:1.78.0 as builder
COPY . /photon-messaging-solana/

RUN --mount=type=cache,target=/photon-messaging-solana/target,sharing=locked --mount=type=cache,target=/usr/local/cargo/registry \
    cargo build --manifest-path=photon-messaging-solana/Cargo.toml \
                --package bridge-extension \
                --package borpa-bridge-extension \
                --package onefunc-extension \
                --package gov-extension \
                --package transmitter-module \
                --release && \
    mkdir /release && \
    cp /photon-messaging-solana/target/release/transmitter-module \
       /photon-messaging-solana/target/release/libonefunc_extension.so \
       /photon-messaging-solana/target/release/libgov_extension.so \
       /photon-messaging-solana/target/release/libborpa_bridge_extension.so \
       /photon-messaging-solana/target/release/libbridge_extension.so /release

FROM ubuntu
COPY --from=builder /release/* \
    /photon-messaging-solana/docker/publisher-config.yml \
    /photon-messaging-solana/docker/listener-config.yml \
    /photon-messaging-solana/docker/watcher-config.yml \
    /photon-messaging-solana/extensions/bridge-ngl.toml \
    /photon-messaging-solana/extensions/bridge-borpa.toml \
    /photon-messaging-solana/docker/executor-config.yml /

RUN mkdir extensions
RUN cp bridge-ngl.toml extensions
RUN cp bridge-borpa.toml extensions

# Listener
#ENTRYPOINT ["/transmitter-module", "listener", "--config", "listener-config.yml"]
# Executor
#ENTRYPOINT ["/transmitter-module", "executor", "--config", "executor-config.yml"]
# Test publisher
#ENTRYPOINT ["/test-publisher", "init-owned-counter", "--config", "publisher-config.yml"]
#ENTRYPOINT ["/test-publisher", "increment-owned-counter", "--value", "2", "--times", "1", "--config", "publisher-config.yml"]
