# rabbit AMQP 0.9.1 settings to connect with and establish a channel
rabbitmq:
    # The server host
    host: localhost
    # The server port. Default: 5672 by [AMQP 0-9-1 spec](https://www.rabbitmq.com/amqp-0-9-1-reference.html).
    port: 5672
    # Exchange name
    exchange: entangle
    # Routing key
    routing_key: to_solana
    # Executor `consumer_tag`
    consumer_tag: solana
    # Queue will optionally be created if doesn't exist and will be used to get signed operations from it
    queue: "signed_operations"
    # User to connect to rabbitmq and be authorized with, it's recommended to set user as env `ENTANGLE_RABBITMQ_USER` but could also be set right here
    # user: guest
    # Password to connect to rabbitmq and be authorized with, it's recommended to set user as env `ENTANGLE_RABBITMQ_PASSWORD` but could also be set right here
    # password: guest
    # Reconnect attempts. The count of times executor will try to recover the connection. Default: 20
    reconnect_attempts: 100
    # Reconnect Timeout. The time between attempts for the listener to try to reconnect. Default: 500
    reconnect_timeout_ms: 1000

# solana interaction settings
solana:
    # Payer is recommended to set payer as env `ENTANGLE_SOLANA_PAYER` but could also be set right here
    # payer: mRazhLmdFRULW1Z6jHcQ2WR4f9eRmjiLvR7R2Yo4LQfvFj5XiN3bwPt6dSUoQfNWpey5VgJaZZWU3vkQmH9ubsY
    # HTTP RPC addresses to connect to read and write to Solana
    read_rpcs:
        -   url: http://127.0.0.1:8899
            ratelimit: 4 # requests per second
    write_rpcs:
        -   url: http://127.0.0.1:8899
            ratelimit: 4 # requests per second
    # The solana client commitment to not continue processing until the given confirmation level happens
    # possible values: processed, confirmed, finalized
    commitment: confirmed
    # A threshold that is expressed in the operation executing attempts. Each 100th attempt balance should be checked.
    check_balance_period: 100
    # A balance threshold to warn if that is bellow the defined value
    warn_balance_lamports: 2000000000
    # A balance threshold to pause operation processing if that is bellow the defined value
    suspend_balance_lamports: 1000000000
    # The attempts to retry an operation if that is in the same status until it is considered as failed and skipped
    executor_attempts: 4

# List of executor extensions registered for solana transaction preprocessing
extensions:
    - target/release/libonefunc_extension.dylib
    - target/release/libgov_extension.dylib

# mongodb is used to store last_processed_block in a persistent way
mongodb:
    # Mongodb uri to connect to
    uri: mongodb://127.0.0.1:27017
    # Mongodb user name
    user: root
    # Mongodb user password
    password: rootpassword
    # Database that is used to get last_processed_block during the retrospective proposal reading
    db: "entangle"
    # The value to update to make the retrospective reading possible in the core transmitter process
    key: "last_processed_block"
