name: CI Workflow

on: [push, pull_request]

jobs:
  clippy:
    runs-on: ubuntu-latest
    container: rust:1.78.0
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        run: |
          rustup default 1.78.0
          rustup component add clippy
      - name: Run Clippy
        run: cargo clippy --all-targets -- -Dwarnings

  tests:
    needs: clippy
    runs-on: ubuntu-latest
    container: rust:1.78.0
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: cargo test --workspace --exclude entangle-photon-sol -- --skip test_send

  build_module:
    needs: tests
    runs-on: ubuntu-latest
    container: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'
      - name: Configure Docker
        run: gcloud auth configure-docker
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/poetic-nova-407814/photon-module:${{ github.ref_name }}.${{ github.run_id }} -t gcr.io/poetic-nova-407814/photon-module:${{ github.ref_name }}.latest -f ./docker/Dockerfile_module .
          docker push gcr.io/poetic-nova-407814/photon-module:${{ github.ref_name }}.${{ github.run_id }}
          docker push gcr.io/poetic-nova-407814/photon-module:${{ github.ref_name }}.latest

  build_solana:
    needs: build_module
    runs-on: ubuntu-latest
    container: gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCLOUD_SERVICE_KEY }}'
      - name: Configure Docker
        run: gcloud auth configure-docker
      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/poetic-nova-407814/photon-solana:${{ github.ref_name }}.${{ github.run_id }} -t gcr.io/poetic-nova-407814/photon-solana:${{ github.ref_name }}.latest -f ./docker/Dockerfile_solana .
          docker push gcr.io/poetic-nova-407814/photon-solana:${{ github.ref_name }}.${{ github.run_id }}
          docker push gcr.io/poetic-nova-407814/photon-solana:${{ github.ref_name }}.latest
